// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKVL.Models;

#nullable disable

namespace TKVL.Migrations
{
    [DbContext(typeof(JobPortalDbContext))]
    [Migration("20260725021200_UpdateGPKDTwoSidesAndYeuCauBoSung")]
    partial class UpdateGPKDTwoSidesAndYeuCauBoSung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TKVL.Models.CV_CauTrucMuc", b =>
                {
                    b.Property<int>("MaCauTruc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauTruc"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaCV")
                        .HasColumnType("int");

                    b.Property<string>("TenMucHienThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCauTruc");

                    b.HasIndex("MaCV");

                    b.ToTable("CV_CauTrucMucs");
                });

            modelBuilder.Entity("TKVL.Models.ChiTietPhanTichAi", b =>
                {
                    b.Property<int>("MaPhanTich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhanTich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanTich"));

                    b.Property<int>("DiemCapBac")
                        .HasColumnType("int")
                        .HasColumnName("diemCapBac");

                    b.Property<string>("DiemConThieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diemConThieu");

                    b.Property<int>("DiemKinhNghiem")
                        .HasColumnType("int")
                        .HasColumnName("diemKinhNghiem");

                    b.Property<int>("DiemKyNang")
                        .HasColumnType("int")
                        .HasColumnName("diemKyNang");

                    b.Property<int>("DiemLinhVuc")
                        .HasColumnType("int")
                        .HasColumnName("diemLinhVuc");

                    b.Property<string>("DiemManhTieuBieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diemManhTieuBieu");

                    b.Property<int>("DiemMatchingTong")
                        .HasColumnType("int")
                        .HasColumnName("diemMatchingTong");

                    b.Property<int>("MaDon")
                        .HasColumnType("int")
                        .HasColumnName("maDon");

                    b.Property<string>("ThongTinHoSoTrichXuatJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thongTinHoSoTrichXuatJson");

                    b.HasKey("MaPhanTich");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.ToTable("ChiTietPhanTichAi", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.ChiTietViTri", b =>
                {
                    b.Property<int>("MaViTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maViTri");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaViTri"));

                    b.Property<string>("Luong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("luong");

                    b.Property<int>("MaNganh")
                        .HasColumnType("int")
                        .HasColumnName("maNganh");

                    b.Property<int>("MaPhuong")
                        .HasColumnType("int")
                        .HasColumnName("maPhuong");

                    b.Property<int>("MaTin")
                        .HasColumnType("int")
                        .HasColumnName("maTin");

                    b.Property<string>("MoTaCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTaCongViec");

                    b.Property<string>("NganhNgheKhac")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nganhNgheKhac");

                    b.Property<string>("QuyenLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quyenLoi");

                    b.Property<int>("SoLuongTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("soLuongTuyen");

                    b.Property<string>("TenViTri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("tenViTri");

                    b.Property<string>("YeuCauUngVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yeuCauUngVien");

                    b.HasKey("MaViTri")
                        .HasName("PK__ChiTietV__1D9EB9AFB5B463F0");

                    b.HasIndex("MaNganh");

                    b.HasIndex("MaPhuong");

                    b.HasIndex("MaTin");

                    b.ToTable("ChiTietViTri", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.CongTy", b =>
                {
                    b.Property<int>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maCongTy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongTy"));

                    b.Property<string>("ChuKyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("GiayPhepKinhDoanhMatSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiayPhepKinhDoanhMatTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maSoThue");

                    b.Property<int>("MaUser")
                        .HasColumnType("int")
                        .HasColumnName("maUser");

                    b.Property<string>("MauEmailInterview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("QuyMo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quyMo");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenCongTy");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.Property<string>("YeuCauBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongTy")
                        .HasName("PK__CongTy__EAECFE7B76A7CB70");

                    b.HasIndex(new[] { "MaUser" }, "UQ__CongTy__18B21FF0E38144C8")
                        .IsUnique();

                    b.HasIndex(new[] { "MaSoThue" }, "UQ__CongTy__6A0F0170C6948BB6")
                        .IsUnique();

                    b.ToTable("CongTy", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.Cv", b =>
                {
                    b.Property<int>("MaCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCv"));

                    b.Property<string>("CustomLayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuCv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duLieuCV");

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("duongDan");

                    b.Property<string>("FontChu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit")
                        .HasColumnName("isPublic");

                    b.Property<string>("MaHex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaUser")
                        .HasColumnType("int")
                        .HasColumnName("maUser");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tieuDe");

                    b.HasKey("MaCv")
                        .HasName("PK__CV__7A3E0CF073B2E13F");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaUser");

                    b.ToTable("CV", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.DanhMucMau", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucMaus");
                });

            modelBuilder.Entity("TKVL.Models.DonUngTuyen", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghiChu");

                    b.Property<int>("MaCv")
                        .HasColumnType("int")
                        .HasColumnName("maCV");

                    b.Property<int>("MaViTri")
                        .HasColumnType("int")
                        .HasColumnName("maViTri");

                    b.Property<DateTime>("NgayNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayNop")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ThuGioiThieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thuGioiThieu");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.HasKey("MaDon")
                        .HasName("PK__DonUngTu__2431086DFCC52540");

                    b.HasIndex("MaCv");

                    b.HasIndex("MaViTri");

                    b.ToTable("DonUngTuyen", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.GiaoDich", b =>
                {
                    b.Property<int>("MaGd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGd"));

                    b.Property<byte>("LoaiGiaoDich")
                        .HasColumnType("tinyint")
                        .HasColumnName("loaiGiaoDich");

                    b.Property<string>("MaGiaoDichDoiTac")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("maGiaoDichDoiTac");

                    b.Property<int?>("MaGoi")
                        .HasColumnType("int")
                        .HasColumnName("maGoi");

                    b.Property<int>("MaUser")
                        .HasColumnType("int")
                        .HasColumnName("maUser");

                    b.Property<DateTime>("NgayGd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayGD")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuongThuc");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soTien");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaGd")
                        .HasName("PK__GiaoDich__7A3E2D67EF992E32");

                    b.HasIndex("MaGoi");

                    b.HasIndex("MaUser");

                    b.ToTable("GiaoDich", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.GoiDichVu", b =>
                {
                    b.Property<int>("MaGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoi"));

                    b.Property<int?>("DonViThoiGian")
                        .HasColumnType("int")
                        .HasColumnName("donViThoiGian");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaKhuyenMai");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("giaTien");

                    b.Property<byte>("LoaiGoi")
                        .HasColumnType("tinyint")
                        .HasColumnName("loaiGoi");

                    b.Property<int>("SoLuotXemCv")
                        .HasColumnType("int")
                        .HasColumnName("soLuotXemCV");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenGoi");

                    b.HasKey("MaGoi")
                        .HasName("PK__GoiDichV__2D87A9A0DF458666");

                    b.ToTable("GoiDichVu", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.JobAlert", b =>
                {
                    b.Property<int>("MaAlert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAlert"));

                    b.Property<int>("MaNganh")
                        .HasColumnType("int");

                    b.Property<int>("MaNganhNavigationMaNganh")
                        .HasColumnType("int");

                    b.Property<int>("MaUser")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("TuKhoaKyNang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAlert");

                    b.HasIndex("MaNganhNavigationMaNganh");

                    b.HasIndex("MaUser");

                    b.ToTable("JobAlerts");
                });

            modelBuilder.Entity("TKVL.Models.KyNang", b =>
                {
                    b.Property<int>("MaKyNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maKyNang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyNang"));

                    b.Property<string>("TenKyNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenKyNang");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangThai");

                    b.HasKey("MaKyNang")
                        .HasName("PK__KyNang__A5BBD21FE9BCB984");

                    b.ToTable("KyNang", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.LichSuMoKhoaCV", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaCv")
                        .HasColumnType("int");

                    b.Property<int>("MaUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMoKhoa")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaCv");

                    b.HasIndex("MaUser");

                    b.ToTable("LichSuMoKhoaCvs");
                });

            modelBuilder.Entity("TKVL.Models.MauCV", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<string>("AnhThumbnail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DanhSachMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsATS")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NgonNgu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaMau");

                    b.ToTable("MauCVs");
                });

            modelBuilder.Entity("TKVL.Models.NganhNghe", b =>
                {
                    b.Property<int>("MaNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maNganh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNganh"));

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenNganh");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangThai");

                    b.HasKey("MaNganh")
                        .HasName("PK__NganhNgh__4E0C021750B7BE5B");

                    b.ToTable("NganhNghe", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.PhanLoaiMau", b =>
                {
                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.HasKey("MaMau", "MaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("PhanLoaiMaus");
                });

            modelBuilder.Entity("TKVL.Models.PhuongXa", b =>
                {
                    b.Property<int>("MaPhuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhuong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuong"));

                    b.Property<int>("MaTp")
                        .HasColumnType("int")
                        .HasColumnName("maTP");

                    b.Property<string>("TenPhuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenPhuong");

                    b.HasKey("MaPhuong")
                        .HasName("PK__PhuongXa__DF98DF6714DE7A6F");

                    b.HasIndex("MaTp");

                    b.ToTable("PhuongXa", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.ThanhPho", b =>
                {
                    b.Property<int>("MaTp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maTP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTp"));

                    b.Property<string>("TenTp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenTP");

                    b.HasKey("MaTp")
                        .HasName("PK__ThanhPho__7A22625BAD627896");

                    b.ToTable("ThanhPho", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.TinDaLuu", b =>
                {
                    b.Property<int>("MaUser")
                        .HasColumnType("int")
                        .HasColumnName("maUser");

                    b.Property<int>("MaViTri")
                        .HasColumnType("int")
                        .HasColumnName("maViTri");

                    b.Property<DateTime>("NgayLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayLuu")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaUser", "MaViTri")
                        .HasName("PK__TinDaLuu__F96BF46BF9E6D8A3");

                    b.HasIndex("MaViTri");

                    b.ToTable("TinDaLuu", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.TinTuyenDung", b =>
                {
                    b.Property<int>("MaTin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maTin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTin"));

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit")
                        .HasColumnName("isPromoted");

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int")
                        .HasColumnName("maCongTy");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayHetHan");

                    b.Property<string>("TieuDeChienDich")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieuDeChienDich");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.HasKey("MaTin")
                        .HasName("PK__TinTuyen__0FC4052A75963FBB");

                    b.HasIndex("MaCongTy");

                    b.ToTable("TinTuyenDung", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.User", b =>
                {
                    b.Property<int>("MaUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUser"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("facebookId");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("googleId");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<int>("LuotXemCvConLai")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<DateTime?>("NgayHetHanGoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoDuVi")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("soDuVi");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trangThai");

                    b.Property<byte>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2)
                        .HasColumnName("vaiTro");

                    b.HasKey("MaUser")
                        .HasName("PK__User__18B21FF1C0EDDC7B");

                    b.HasIndex(new[] { "GoogleId" }, "UQ__User__0DA2E4829AC45A41")
                        .IsUnique()
                        .HasFilter("[googleId] IS NOT NULL");

                    b.HasIndex(new[] { "FacebookId" }, "UQ__User__1DCE2AA87028DFD3")
                        .IsUnique()
                        .HasFilter("[facebookId] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E61649BE61696")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ViTriKyNang", b =>
                {
                    b.Property<int>("MaViTri")
                        .HasColumnType("int")
                        .HasColumnName("maViTri");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int")
                        .HasColumnName("maKyNang");

                    b.HasKey("MaViTri", "MaKyNang")
                        .HasName("PK__ViTri_Ky__F7C5048EA33CCCA9");

                    b.HasIndex("MaKyNang");

                    b.ToTable("ViTri_KyNang", (string)null);
                });

            modelBuilder.Entity("TKVL.Models.CV_CauTrucMuc", b =>
                {
                    b.HasOne("TKVL.Models.Cv", "CV")
                        .WithMany("CauTrucMucs")
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");
                });

            modelBuilder.Entity("TKVL.Models.ChiTietPhanTichAi", b =>
                {
                    b.HasOne("TKVL.Models.DonUngTuyen", "MaDonNavigation")
                        .WithOne("ChiTietPhanTichAi")
                        .HasForeignKey("TKVL.Models.ChiTietPhanTichAi", "MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietPhanTichAi_DonUngTuyen");

                    b.Navigation("MaDonNavigation");
                });

            modelBuilder.Entity("TKVL.Models.ChiTietViTri", b =>
                {
                    b.HasOne("TKVL.Models.NganhNghe", "MaNganhNavigation")
                        .WithMany("ChiTietViTris")
                        .HasForeignKey("MaNganh")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietViTri_NganhNghe");

                    b.HasOne("TKVL.Models.PhuongXa", "MaPhuongNavigation")
                        .WithMany("ChiTietViTris")
                        .HasForeignKey("MaPhuong")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietViTri_PhuongXa");

                    b.HasOne("TKVL.Models.TinTuyenDung", "MaTinNavigation")
                        .WithMany("ChiTietViTris")
                        .HasForeignKey("MaTin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietViTri_TinTuyenDung");

                    b.Navigation("MaNganhNavigation");

                    b.Navigation("MaPhuongNavigation");

                    b.Navigation("MaTinNavigation");
                });

            modelBuilder.Entity("TKVL.Models.CongTy", b =>
                {
                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithOne("CongTy")
                        .HasForeignKey("TKVL.Models.CongTy", "MaUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CongTy_User");

                    b.Navigation("MaUserNavigation");
                });

            modelBuilder.Entity("TKVL.Models.Cv", b =>
                {
                    b.HasOne("TKVL.Models.MauCV", "MaMauNavigation")
                        .WithMany("Cvs")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Cv_MauCV");

                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithMany("Cvs")
                        .HasForeignKey("MaUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CV_User");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaUserNavigation");
                });

            modelBuilder.Entity("TKVL.Models.DonUngTuyen", b =>
                {
                    b.HasOne("TKVL.Models.Cv", "MaCvNavigation")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("MaCv")
                        .IsRequired()
                        .HasConstraintName("FK_DonUngTuyen_CV");

                    b.HasOne("TKVL.Models.ChiTietViTri", "MaViTriNavigation")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("MaViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DonUngTuyen_ChiTietViTri");

                    b.Navigation("MaCvNavigation");

                    b.Navigation("MaViTriNavigation");
                });

            modelBuilder.Entity("TKVL.Models.GiaoDich", b =>
                {
                    b.HasOne("TKVL.Models.GoiDichVu", "MaGoiNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaGoi")
                        .HasConstraintName("FK_GiaoDich_GoiDichVu");

                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaUser")
                        .IsRequired()
                        .HasConstraintName("FK_GiaoDich_User");

                    b.Navigation("MaGoiNavigation");

                    b.Navigation("MaUserNavigation");
                });

            modelBuilder.Entity("TKVL.Models.JobAlert", b =>
                {
                    b.HasOne("TKVL.Models.NganhNghe", "MaNganhNavigation")
                        .WithMany()
                        .HasForeignKey("MaNganhNavigationMaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithMany()
                        .HasForeignKey("MaUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaNganhNavigation");

                    b.Navigation("MaUserNavigation");
                });

            modelBuilder.Entity("TKVL.Models.LichSuMoKhoaCV", b =>
                {
                    b.HasOne("TKVL.Models.Cv", "MaCvNavigation")
                        .WithMany()
                        .HasForeignKey("MaCv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithMany()
                        .HasForeignKey("MaUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaCvNavigation");

                    b.Navigation("MaUserNavigation");
                });

            modelBuilder.Entity("TKVL.Models.PhanLoaiMau", b =>
                {
                    b.HasOne("TKVL.Models.DanhMucMau", "DanhMucMauNavigation")
                        .WithMany("PhanLoaiMaus")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PhanLoaiMau_DanhMuc");

                    b.HasOne("TKVL.Models.MauCV", "MauCVNavigation")
                        .WithMany("PhanLoaiMaus")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PhanLoaiMau_MauCV");

                    b.Navigation("DanhMucMauNavigation");

                    b.Navigation("MauCVNavigation");
                });

            modelBuilder.Entity("TKVL.Models.PhuongXa", b =>
                {
                    b.HasOne("TKVL.Models.ThanhPho", "MaTpNavigation")
                        .WithMany("PhuongXas")
                        .HasForeignKey("MaTp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PhuongXa_ThanhPho");

                    b.Navigation("MaTpNavigation");
                });

            modelBuilder.Entity("TKVL.Models.TinDaLuu", b =>
                {
                    b.HasOne("TKVL.Models.User", "MaUserNavigation")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("MaUser")
                        .IsRequired()
                        .HasConstraintName("FK_TinDaLuu_User");

                    b.HasOne("TKVL.Models.ChiTietViTri", "MaViTriNavigation")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("MaViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TinDaLuu_ChiTietViTri");

                    b.Navigation("MaUserNavigation");

                    b.Navigation("MaViTriNavigation");
                });

            modelBuilder.Entity("TKVL.Models.TinTuyenDung", b =>
                {
                    b.HasOne("TKVL.Models.CongTy", "MaCongTyNavigation")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("MaCongTy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TinTuyenDung_CongTy");

                    b.Navigation("MaCongTyNavigation");
                });

            modelBuilder.Entity("ViTriKyNang", b =>
                {
                    b.HasOne("TKVL.Models.KyNang", null)
                        .WithMany()
                        .HasForeignKey("MaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ViTriKyNang_KyNang");

                    b.HasOne("TKVL.Models.ChiTietViTri", null)
                        .WithMany()
                        .HasForeignKey("MaViTri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ViTriKyNang_ChiTietViTri");
                });

            modelBuilder.Entity("TKVL.Models.ChiTietViTri", b =>
                {
                    b.Navigation("DonUngTuyens");

                    b.Navigation("TinDaLuus");
                });

            modelBuilder.Entity("TKVL.Models.CongTy", b =>
                {
                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("TKVL.Models.Cv", b =>
                {
                    b.Navigation("CauTrucMucs");

                    b.Navigation("DonUngTuyens");
                });

            modelBuilder.Entity("TKVL.Models.DanhMucMau", b =>
                {
                    b.Navigation("PhanLoaiMaus");
                });

            modelBuilder.Entity("TKVL.Models.DonUngTuyen", b =>
                {
                    b.Navigation("ChiTietPhanTichAi");
                });

            modelBuilder.Entity("TKVL.Models.GoiDichVu", b =>
                {
                    b.Navigation("GiaoDiches");
                });

            modelBuilder.Entity("TKVL.Models.MauCV", b =>
                {
                    b.Navigation("Cvs");

                    b.Navigation("PhanLoaiMaus");
                });

            modelBuilder.Entity("TKVL.Models.NganhNghe", b =>
                {
                    b.Navigation("ChiTietViTris");
                });

            modelBuilder.Entity("TKVL.Models.PhuongXa", b =>
                {
                    b.Navigation("ChiTietViTris");
                });

            modelBuilder.Entity("TKVL.Models.ThanhPho", b =>
                {
                    b.Navigation("PhuongXas");
                });

            modelBuilder.Entity("TKVL.Models.TinTuyenDung", b =>
                {
                    b.Navigation("ChiTietViTris");
                });

            modelBuilder.Entity("TKVL.Models.User", b =>
                {
                    b.Navigation("CongTy");

                    b.Navigation("Cvs");

                    b.Navigation("GiaoDiches");

                    b.Navigation("TinDaLuus");
                });
#pragma warning restore 612, 618
        }
    }
}
